#+TITLE: DOOM Emacs Configuration
#+PROPERTY: header-args :tangle config.el

* Meta

Documentation: https://github.com/hlissner/doom-emacs/blob/develop/modules/config/literate/README.org
Inspired by https://raw.githubusercontent.com/daviwil/dotfiles/master/Emacs.org
Examples:
- https://github.com/hlissner/doom-emacs-private/blob/master/config.el

Tangle with command 'org-babel-tangle'

** TODO Commands on SPC SPC
** TODO Don't ask on quit
** TODO Update Table of Contents
** TODO How to eval codeblocks?
** TODO Limit file watchers for happygast project

* Table of Contents
:PROPERTIES:
:TOC:      :include all :ignore this
:END:
:CONTENTS:
:END:
* General Configuration

** Doom

#+BEGIN_SRC elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;;           DO NOT MODIFY!
;;       tangeled from config.org

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Witoslaw Koczewski"
      user-mail-address "wi@koczewski.de")

(setq doom-localleader-key ",")

(print "!!! doom")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))




;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+END_SRC

** Line Numbers

This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.

#+BEGIN_SRC elisp

(print "!!! line numbers")

(setq display-line-numbers-type nil)

#+END_SRC

** Scrolling

#+BEGIN_SRC elisp

(setq scroll-conservatively 101
      scroll-margin 12
      scroll-preserve-screen-position 't)

#+END_SRC

** Theme and Fonts

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+BEGIN_SRC elisp

(print "!!! theme")

(setq doom-theme 'doom-one)
;; (setq doom-theme 'doom-dracula)

(setq doom-font (font-spec :family "Fira Code" :size 14)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 15)
      ivy-posframe-font (font-spec :family "Fira Code" :size 17))

#+END_SRC

** Exit without Confirmation

#+BEGIN_SRC elisp

(setq confirm-kill-emacs nil)

#+END_SRC


* Keyboard Bindings

** ESC cancels all

#+begin_src elisp

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

** SPC SPC lists commands

#+begin_src elisp

(map! :leader
      :desc "List commands"
      "SPC"  #'execute-extended-command)

#+end_src

** Navigation

#+BEGIN_SRC elisp

(map! :map global-map
      :n "C-h" #'evil-prev-buffer
      :n "C-l" #'evil-next-buffer
      :n "C-j" #'evil-jump-forward
      :n "C-k" #'evil-jump-backward
      )

#+END_SRC

** Comments

#+begin_src elisp

(map! :map global-map
      :nv ";" #'evilnc-comment-or-uncomment-lines)

#+end_src

** LISP

#+BEGIN_SRC elisp

(map! :map global-map
      :n "M-h"  #'paredit-forward-barf-sexp)
(map! :map global-map
      :n "M-l"  #'paredit-forward-slurp-sexp)

;; (map! :localleader
      ;; ",a"  #'evil-cp-insert-at-end-of-form
      ;; ",i" 'evil-cp-insert-at-beginning-of-form
      ;; "(" #'sp-wrap-round)

#+END_SRC

* Org

#+BEGIN_SRC elisp

(print "[config.org] Org")

(setq org-directory "~/org/")

#+END_SRC

* LSP

- https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

#+BEGIN_SRC elisp

(print "[config.org] LSP")

(with-eval-after-load 'lsp-mode
  (print "[config.org] with-eval-after-load lsp-mode")
  (setq lsp-ui-imenu-enable t
        lsp-ui-doc-enable t
        lsp-ui-sideline-show-code-actions nil
        lsp-lens-enable t
        lsp-enable-symbol-highlighting nil
        ;; lsp-enable-file-watchers nil
        ;; +lsp-prompt-to-install-server 'quiet
        )
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\firebase\\'")
  )

#+END_SRC
